### ISSUE TITLE
Could i ask one question?: What is the difference between /xnu/libkern/ and /xnu/libkern/libkern/ ?

### ISSUE THREAD

**Issue by andypeker** [opensource-apple/xnu#1]
could you answer the question ? thank you ~

**Comment by opensource-apple** [comment]
Sorry, I don't know.

Suggest you to ask in https://lists.apple.com/mailman/listinfo/darwin-dev , good luck.

**Comment by steakknife** [comment]
@andypeker libkern is like a kernel-land "libc"... a bucket of misc. C/C++ utilities which don't depend on anything else. That's all I know.

- `/xnu/libkern/libkern/` -> `/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/libkern/`
- `/xnu/libkern/` ->  `/System/Library/PrelinkedKernels/prelinkedkernel` / `/System/Library/Kernels/kernel`
