### ISSUE TITLE
A bug in strstr which will cause dump!!

### ISSUE THREAD

**Issue by muthursyamburi** [opensource-apple/xnu#5]
Looks like there is a bug in the below strstr() which causes a dump:

```
__private_extern__ const char *
strstr(const char *in, const char *str)
{
    char c;
    size_t len;

    c = *str++;
    if (!c)
        return (const char *) in;   // Trivial empty string case

    len = strlen(str);
    do {
        char sc;

        do {
            sc = *in++;
            if (!sc)
                return (char *) 0;
        } while (sc != c);
    } while (strncmp(in, str, len) != 0);

    return (const char *) (in - 1);
}
```

The above code handles NULL for the "str" param, but not for "in"!!!
That means, if I invoke it like this `strstr(NULL, "Hello");`, instead of gracefully existing by returning NULL, it will try to de-reference the NULL leading to a dump.

Not sure if this is an old/dead code base. But if this is in production, it is dangerous.

**Comment by muthursyamburi** [comment]
This is how I would fix the issue:
```
len = strlen(str);
// The below two lines are the suggested fix!
if ( !in )         
    return in;  // Trivial case of input string being empty
do {
....
....
```
I am on a Linux box and facing some issues to compile the xnu here. Not that much well versed with xnu code base as this is my first time. So dont know how to fix those errors. Googling for it is taking me to different levels.

**Comment by boranyldrm** [comment]
I made a pull request and I believe I solved the issue. Can you also check it?

**Comment by muthursyamburi** [comment]
I reviewed and provided a comment. Please revisit and recheck in the code, if you too agree with my point. Here is the comment link: [https://github.com/opensource-apple/xnu/pull/6#pullrequestreview-6144902](url)

**Comment by opensource-apple** [comment]
If any issue, pls contact with https://opensource.apple.com and relative mailing lists. Thanks.
